"""Removed location and owner from Stores

Revision ID: 14cb219a341c
Revises: 56a48d7e041b
Create Date: 2025-07-21 23:24:47.264629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14cb219a341c'
down_revision: Union[str, Sequence[str], None] = '56a48d7e041b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'owner')
    op.drop_column('stores', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('stores', sa.Column('owner', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
