"""Created owner_id ForeignKey

Revision ID: 78d0d2d62e69
Revises: a2ba99ae370b
Create Date: 2025-07-21 23:50:34.245673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78d0d2d62e69'
down_revision: Union[str, Sequence[str], None] = 'a2ba99ae370b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'stores', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stores', type_='foreignkey')
    # ### end Alembic commands ###
