"""Created owner_id on table Stores

Revision ID: a2ba99ae370b
Revises: 14cb219a341c
Create Date: 2025-07-21 23:40:44.646441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2ba99ae370b'
down_revision: Union[str, Sequence[str], None] = '14cb219a341c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('owner_id', sa.Integer(), nullable=False, server_default='1'))
    op.alter_column('stores', 'owner_id', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'owner_id')
    # ### end Alembic commands ###
